# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Adam Walsh
tagline:          'My Personal Website'
description:      'A place for me to post whatever I want.'
url:              http://walshie4.github.io

author:
  name:           'Adam Walsh'
  github:         'walshie4'
  url:            https://walshie4.github.io

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/walshie4/walshie4.github.io
